/*
 * 1. DBFlow 설정
 * DBF_DB_CONFIG: 데이터베이스(스키마 기준) 설정
 * DBF_USER: 사용자 설정(1명만 등록)
 */
CREATE TABLE DBF_DB_CONFIG
(
    DB_CONFIG_ID      INTEGER PRIMARY KEY AUTOINCREMENT,
    DB_ALIAS          TEXT    NOT NULL,
    DB_TYPE           TEXT    NOT NULL,
    DB_HOST           TEXT    NOT NULL,
    DB_PORT           INTEGER NOT NULL,
    DB_NAME           TEXT    NOT NULL,
    DB_SCHEMA         TEXT    NOT NULL,
    DB_USER           TEXT    NOT NULL,
    DB_PASSWORD       TEXT    NOT NULL,
    USE_YN            INTEGER NOT NULL DEFAULT 1,
    CREATED_AT        TEXT    NOT NULL,
    UPDATED_AT        TEXT    NOT NULL,
    UNIQUE (DB_ALIAS),
    UNIQUE (DB_HOST, DB_PORT, DB_NAME, DB_SCHEMA)
);

CREATE TABLE DBF_USER
(
    USER_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    DB_CONFIG_ID INTEGER,
    USER_NAME TEXT NOT NULL,
    USER_EMAIL TEXT NOT NULL,
    USE_YN INTEGER NOT NULL DEFAULT 1,
    CREATED_AT TEXT NOT NULL,
    UPDATED_AT TEXT NOT NULL,
    CHECK (USE_YN IN (0, 1))
);

/*
 * 2. DBFlow 작업 결과물 비교용 테이블들
 * DBF_WORK_TARGET: 테이블 단위 목록
 * DBF_WORK_COMPONENT: 컬럼/인덱스/제약조건 단위 목록
 * DBF_WORK_CHANGE: 변경된 데이터 상세 목록
 */
CREATE TABLE DBF_WORK_TARGET
(
    WORK_TARGET_ID    INTEGER PRIMARY KEY AUTOINCREMENT,
    DB_CONFIG_ID      INTEGER NOT NULL,
    OBJECT_TYPE       TEXT NOT NULL CHECK (OBJECT_TYPE IN ('TABLE', 'VIEW')),
    OBJECT_NAME       TEXT NOT NULL,
    OBJECT_COMMENT    TEXT,
    CHANGE_TYPE       TEXT NOT NULL CHECK (CHANGE_TYPE IN ('ADD', 'MOD', 'DEL')),
    COMPARED_AT       TEXT NOT NULL,
    FOREIGN KEY (DB_CONFIG_ID) REFERENCES DBF_DB_CONFIG (DB_CONFIG_ID) ON DELETE CASCADE
);

CREATE TABLE DBF_WORK_COMPONENT
(
    WORK_COMPONENT_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    WORK_TARGET_ID INTEGER NOT NULL,
    COMPONENT_TYPE TEXT NOT NULL CHECK (COMPONENT_TYPE IN ('TABLE', 'COLUMN')),
    COMPONENT_NAME TEXT NOT NULL,
    COMPONENT_COMMENT TEXT,
    CHANGE_TYPE TEXT NOT NULL CHECK (CHANGE_TYPE IN ('ADD', 'MOD', 'DEL')),
    FOREIGN KEY (WORK_TARGET_ID) REFERENCES DBF_WORK_TARGET (WORK_TARGET_ID)
);

CREATE TABLE DBF_WORK_CHANGE
(
    WORK_CHANGE_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    WORK_COMPONENT_ID INTEGER NOT NULL,
    CHANGE_COLUMN TEXT NOT NULL,
    BEFORE_VALUE TEXT,
    AFTER_VALUE TEXT,
    FOREIGN KEY (WORK_COMPONENT_ID) REFERENCES DBF_WORK_COMPONENT (WORK_COMPONENT_ID),
    CHECK (CHANGE_COLUMN IN ('TABLE_COMMENT', 'COLUMN_NAME', 'DATA_TYPE', 'DATA_LENGTH', 'DATA_SCALE',
                             'NULLABLE_YN', 'DEFAULT_VALUE', 'IDENTITY_YN', 'IDENTITY_TYPE', 'COLUMN_ORDER', 'COLUMN_COMMENT')
          )
);

/*
 * 3. DBFlow 커밋들 이력 목록
 * DBF_COMMIT_LOG: 변경 작업 했던 커밋 이력 목록 테이블
 * DBF_COMMIT_TARGET: 커밋한 테이블 단위 목록
 * DBF_COMMIT_COMPONENT: 커밋한 컬럼/인덱스/제약조건 단위 목록
 * DBF_COMMIT_CHANGE: 커밋한 변경된 데이터 상세 목록
 */
CREATE TABLE DBF_COMMIT_LOG
(
    COMMIT_LOG_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    DB_CONFIG_ID INTEGER NOT NULL,
    COMMIT_TITLE TEXT NOT NULL,
    COMMIT_CONTENT TEXT,
    USER_ID INTEGER NOT NULL,
    COMMIT_CREATED_AT TEXT NOT NULL,
    FOREIGN KEY (DB_CONFIG_ID) REFERENCES DBF_DB_CONFIG (DB_CONFIG_ID),
    FOREIGN KEY (USER_ID) REFERENCES DBF_USER (USER_ID)
);

CREATE TABLE DBF_COMMIT_TARGET
(
    COMMIT_TARGET_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    COMMIT_LOG_ID INTEGER NOT NULL,
    DB_CONFIG_ID INTEGER NOT NULL,
    OBJECT_TYPE TEXT NOT NULL,
    OBJECT_NAME TEXT NOT NULL,
    OBJECT_COMMENT TEXT,
    CHANGE_TYPE TEXT NOT NULL,
    FOREIGN KEY (COMMIT_LOG_ID) REFERENCES DBF_COMMIT_LOG (COMMIT_LOG_ID),
    FOREIGN KEY (DB_CONFIG_ID) REFERENCES DBF_DB_CONFIG (DB_CONFIG_ID),
    CHECK (OBJECT_TYPE IN ('TABLE', 'VIEW')),
    CHECK (CHANGE_TYPE IN ('ADD', 'MOD', 'DEL'))
);

CREATE TABLE DBF_COMMIT_COMPONENT
(
    COMMIT_COMPONENT_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    COMMIT_TARGET_ID INTEGER NOT NULL,
    COMPONENT_TYPE TEXT NOT NULL,
    COMPONENT_NAME TEXT NOT NULL,
    COMPONENT_COMMENT TEXT,
    CHANGE_TYPE TEXT NOT NULL,
    FOREIGN KEY (COMMIT_TARGET_ID) REFERENCES DBF_COMMIT_TARGET (COMMIT_TARGET_ID),
    CHECK (COMPONENT_TYPE IN ('TABLE','COLUMN','INDEX','CONSTRAINT')),
    CHECK (CHANGE_TYPE IN ('ADD','MOD','DEL'))
);

CREATE TABLE DBF_COMMIT_CHANGE
(
    COMMIT_CHANGE_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    COMMIT_COMPONENT_ID INTEGER NOT NULL,
    CHANGE_COLUMN TEXT NOT NULL,
    BEFORE_VALUE TEXT,
    AFTER_VALUE TEXT,
    FOREIGN KEY (COMMIT_COMPONENT_ID) REFERENCES DBF_COMMIT_COMPONENT (COMMIT_COMPONENT_ID),
    CHECK (CHANGE_COLUMN IN ('TABLE_NAME', 'TABLE_COMMENT', 'COLUMN_NAME', 'DATA_TYPE', 'DATA_LENGTH', 'DATA_SCALE',
                             'NULLABLE_YN', 'DEFAULT_VALUE', 'IDENTITY_YN', 'IDENTITY_TYPE', 'COLUMN_ORDER', 'COLUMN_COMMENT')
          )
);

/*
 * 4. DBFlow DB작업 후 수집한 오브젝트 테이블
 * DBF_COLLECT_TABLE_SNAPSHOT: 수집한 테이블 목록
 * DBF_COLLECT_COLUMN_SNAPSHOT: 수집한 컬럼 목록
 * DBF_COLLECT_INDEX_SNAPSHOT: 수집한 인덱스 목록
 */
CREATE TABLE DBF_COLLECT_TABLE_SNAPSHOT
(
    COLLECT_TABLE_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    DB_CONFIG_ID INTEGER NOT NULL,
    TABLE_NAME TEXT NOT NULL,
    TABLE_COMMENT TEXT,
    TABLE_TYPE TEXT NOT NULL,
    OWNER_NAME TEXT NOT NULL,
    FOREIGN KEY (DB_CONFIG_ID) REFERENCES DBF_DB_CONFIG (DB_CONFIG_ID),
    CHECK (TABLE_TYPE IN ('TABLE', 'VIEW'))
);

CREATE TABLE DBF_COLLECT_COLUMN_SNAPSHOT
(
    COLLECT_COLUMN_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    COLLECT_TABLE_ID INTEGER NOT NULL,
    COLUMN_NAME TEXT NOT NULL,
    COLUMN_COMMENT TEXT,
    COLUMN_ORDER INTEGER NOT NULL,
    DATA_TYPE TEXT NOT NULL,
    DATA_LENGTH INTEGER,
    DATA_SCALE INTEGER,
    NULLABLE_YN INTEGER NOT NULL,
    DEFAULT_VALUE TEXT,
    IDENTITY_YN INTEGER,
    IDENTITY_TYPE TEXT,
    FOREIGN KEY (COLLECT_TABLE_ID) REFERENCES DBF_COLLECT_TABLE_SNAPSHOT (COLLECT_TABLE_ID),
    CHECK (NULLABLE_YN IN (0, 1)),
    CHECK (IDENTITY_YN IS NULL OR IDENTITY_YN IN (0, 1)),
    CHECK (IDENTITY_TYPE IS NULL OR IDENTITY_TYPE IN ('ALWAYS', 'BY_DEFAULT'))
);

CREATE TABLE DBF_COLLECT_INDEX_SNAPSHOT
(
    COLLECT_INDEX_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    COLLECT_TABLE_ID INTEGER NOT NULL,
    INDEX_NAME TEXT NOT NULL,
    INDEX_COMMENT TEXT,
    INDEX_TYPE TEXT NOT NULL DEFAULT 'BTREE',
    INDEX_COLUMNS TEXT NOT NULL,
    UNIQUE_YN INTEGER NOT NULL,
    FOREIGN KEY (COLLECT_TABLE_ID) REFERENCES DBF_COLLECT_TABLE_SNAPSHOT (COLLECT_TABLE_ID),
    CHECK (INDEX_TYPE IN ('BTREE', 'HASH', 'GIN', 'GIST', 'SPGIST', 'BRIN')),
    CHECK (UNIQUE_YN IN (0, 1))
);

/*
 * 5. DBFlow 커밋한 오브젝트 테이블(현재 최종 오브젝트들)
 * DBF_CURRENT_TABLE_SNAPSHOT: 현재 테이블
 * DBF_CURRENT_COLUMN_SNAPSHOT: 현재 컬럼
 * DBF_CURRENT_INDEX_SNAPSHOT: 현재 인덱스
 */
CREATE TABLE DBF_CURRENT_TABLE_SNAPSHOT
(
    CURRENT_TABLE_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    COMMIT_LOG_ID INTEGER NOT NULL,
    DB_CONFIG_ID INTEGER NOT NULL,
    TABLE_NAME TEXT NOT NULL,
    TABLE_COMMENT TEXT,
    TABLE_TYPE TEXT NOT NULL,
    OWNER_NAME TEXT NOT NULL,
    FOREIGN KEY (COMMIT_LOG_ID) REFERENCES DBF_COMMIT_LOG (COMMIT_LOG_ID),
    FOREIGN KEY (DB_CONFIG_ID) REFERENCES DBF_DB_CONFIG (DB_CONFIG_ID),
    CHECK (TABLE_TYPE IN ('TABLE', 'VIEW'))
);

CREATE TABLE DBF_CURRENT_COLUMN_SNAPSHOT
(
    CURRENT_COLUMN_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    CURRENT_TABLE_ID INTEGER NOT NULL,
    COLUMN_NAME TEXT NOT NULL,
    COLUMN_COMMENT TEXT,
    COLUMN_ORDER INTEGER NOT NULL,
    DATA_TYPE TEXT NOT NULL,
    DATA_LENGTH INTEGER,
    DATA_SCALE INTEGER,
    NULLABLE_YN INTEGER NOT NULL,
    DEFAULT_VALUE TEXT,
    IDENTITY_YN INTEGER,
    IDENTITY_TYPE TEXT,
    FOREIGN KEY (CURRENT_TABLE_ID) REFERENCES DBF_CURRENT_TABLE_SNAPSHOT (CURRENT_TABLE_ID),
    CHECK (NULLABLE_YN IN (0, 1)),
    CHECK (IDENTITY_YN IS NULL OR IDENTITY_YN IN (0, 1)),
    CHECK (IDENTITY_TYPE IS NULL OR IDENTITY_TYPE IN ('ALWAYS', 'BY_DEFAULT'))
);

CREATE TABLE DBF_CURRENT_INDEX_SNAPSHOT
(
    CURRENT_INDEX_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    CURRENT_TABLE_ID INTEGER NOT NULL,
    INDEX_NAME TEXT NOT NULL,
    INDEX_COMMENT TEXT,
    INDEX_TYPE TEXT NOT NULL DEFAULT 'BTREE',
    INDEX_COLUMNS TEXT NOT NULL,
    UNIQUE_YN INTEGER NOT NULL,
    FOREIGN KEY (CURRENT_TABLE_ID) REFERENCES DBF_CURRENT_TABLE_SNAPSHOT (CURRENT_TABLE_ID),
    CHECK (INDEX_TYPE IN ('BTREE', 'HASH', 'GIN', 'GIST', 'SPGIST', 'BRIN')),
    CHECK (UNIQUE_YN IN (0, 1))
);

/*
 * 6. DBFlow 커밋했던 이력 오브젝트 테이블(이력 오브젝트들)
 * 커밋 시 반드시 해당 테이블들에다가 데이터를 남겨야한다.
 * DBF_HISTORY_TABLE_SNAPSHOT: 이력 테이블
 * DBF_HISTORY_COLUMN_SNAPSHOT: 이력 컬럼
 * DBF_HISTORY_INDEX_SNAPSHOT: 이력 인덱스
 */
CREATE TABLE DBF_HISTORY_TABLE_SNAPSHOT
(
    HISTORY_TABLE_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    COMMIT_LOG_ID INTEGER NOT NULL,
    DB_CONFIG_ID INTEGER NOT NULL,
    TABLE_NAME TEXT NOT NULL,
    TABLE_COMMENT TEXT,
    TABLE_TYPE TEXT NOT NULL,
    OWNER_NAME TEXT NOT NULL,
    TABLE_DELETED_YN INTEGER NOT NULL DEFAULT 0,
    FOREIGN KEY (COMMIT_LOG_ID) REFERENCES DBF_COMMIT_LOG (COMMIT_LOG_ID),
    FOREIGN KEY (DB_CONFIG_ID) REFERENCES DBF_DB_CONFIG (DB_CONFIG_ID),
    CHECK (TABLE_TYPE IN ('TABLE', 'VIEW')),
    CHECK (TABLE_DELETED_YN IN (0, 1))
);

CREATE TABLE DBF_HISTORY_COLUMN_SNAPSHOT
(
    HISTORY_COLUMN_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    HISTORY_TABLE_ID INTEGER NOT NULL,
    COLUMN_NAME TEXT NOT NULL,
    COLUMN_COMMENT TEXT,
    COLUMN_ORDER INTEGER NOT NULL,
    DATA_TYPE TEXT NOT NULL,
    DATA_LENGTH INTEGER,
    DATA_SCALE INTEGER,
    NULLABLE_YN INTEGER NOT NULL,
    DEFAULT_VALUE TEXT,
    IDENTITY_YN INTEGER,
    IDENTITY_TYPE TEXT,
    FOREIGN KEY (HISTORY_TABLE_ID) REFERENCES DBF_HISTORY_TABLE_SNAPSHOT (HISTORY_TABLE_ID),
    CHECK (NULLABLE_YN IN (0, 1)),
    CHECK (IDENTITY_YN IS NULL OR IDENTITY_YN IN (0, 1)),
    CHECK (IDENTITY_TYPE IS NULL OR IDENTITY_TYPE IN ('ALWAYS', 'BY_DEFAULT'))
);

CREATE TABLE DBF_HISTORY_INDEX_SNAPSHOT
(
    HISTORY_INDEX_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    HISTORY_TABLE_ID INTEGER NOT NULL,
    INDEX_NAME TEXT NOT NULL,
    INDEX_COMMENT TEXT,
    INDEX_TYPE TEXT NOT NULL DEFAULT 'BTREE',
    INDEX_COLUMNS TEXT NOT NULL,
    UNIQUE_YN INTEGER NOT NULL,
    FOREIGN KEY (HISTORY_TABLE_ID) REFERENCES DBF_HISTORY_TABLE_SNAPSHOT (HISTORY_TABLE_ID),
    CHECK (INDEX_TYPE IN ('BTREE', 'HASH', 'GIN', 'GIST', 'SPGIST', 'BRIN')),
    CHECK (UNIQUE_YN IN (0, 1))
);
