runtime.vendor=Azul Zulu
runtime.java.version=17.0.17+10
runtime.zulu.version=17.62.17
runtime.os=macos
runtime.arch=arm64
runtime.package.type=jre
runtime.archive=zulu17.62.17-ca-jre17.0.17-macosx_aarch64.zip
runtime.download.url=https://cdn.azul.com/zulu/bin/zulu17.62.17-ca-jre17.0.17-macosx_aarch64.zip
runtime.sha256=f33bdd918376f53badb7360f727507435f2d670b3439de76f537d1415960d905
